### ISSUE TITLE
Option to switch off file logging.

### ISSUE THREAD

**Issue by nitred** [ansrivas/pylogging#8]
In many parts of my code base I use the logging library. However when I want to run my code in a notebook or only want to test parts of my code, I'd like to be able to switch off all file logging.

This also means I would like to not pass arguments to `setup_logger` that have anything to do with file logging for example the `log_dir` or `file_handler_type` or at least be able to pass `None`.

**Comment by ansrivas** [comment]
Thank you for reporting this. This is indeed a bug. If `allow_file_logging` is `False` we don't even need to initialize `file_handler_type`.

**Comment by ansrivas** [comment]
Fixed in #9
